version: "3.0"

services:
  # app:
  #   build: ./fad
  #   image: fad-application
  #   command: npm run dev
  #   expose:
  #     - 8080
  #   ports:
  #     - "8080:8080"
  strapi:
    container_name: strapi
    build: ./fad-strapi
    image: strapi:latest
    restart: unless-stopped
    env_file: ./fad-strapi/.env
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: fad-strapi
      DATABASE_USERNAME: fadstrapi
      DATABASE_PASSWORD: Strapi2024!
      JWT_SECRET: KuFguJfy7oHuN+z8lIxMRg==
      ADMIN_JWT_SECRET: DXRxNFfJ8CCovhD6wJog2Q==
      APP_KEYS: grsGY/VhpTT11jTXTgdhNw==,fLe6WOmWJNkjCpVIU6U6zg==,5kZcDeMFAq5IjrhJI7gLhQ==,NxQOutvBpvANmkDchGy6jw==
      NODE_ENV: ${NODE_ENV}
    volumes:
      # - ./fad-strapi/config:/opt/strapi/config
      # - ./fad-strapi/src:/opt/strapi/src
      # - ./fad-strapi/package.json:/opt/package.json
      # - ./fad-strapi/yarn.lock:/opt/yarn.lock
      # - ./fad-strapi/.env:/opt/strapi/.env
      # - ./fad-strapi/public/uploads:/opt/strapi/public/uploads
      - ./fad-strapi:/usr/src/api/fad-strapi
    ports:
      - "1337:1337"
    depends_on:
      - postgres
    expose:
      - 1337
  nginx:
    build: ./nginx
    image: nginx
    volumes:
      - ./static/:/app/static/
      - ./nginx/key:/etc/nginx/ssl
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - strapi
  postgres:
    container_name: strapi-database
    #platform: linux/amd64 #for platform error on Apple M1 chips
    image: postgres:12.0-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: fadstrapi
      POSTGRES_PASSWORD: Strapi2024!
      POSTGRES_DB: fad-strapi
    volumes:
      - strapi-data:/var/lib/postgresql/data/ #using a volume
      #- ./data:/var/lib/postgresql/data/ # if you want to use a bind folder
    ports:
      - "5432:5432"

volumes:
  strapi-data:

# networks:
#   strapi:
#     name: Strapi
#     driver: bridge